### ISSUE TITLE
Keywords Browser Can Not, Selenium Can

### ISSUE THREAD

**Issue by Snooz82** [MarketSquare/robotframework-browser#191]
**Is your feature request related to a problem? Please describe.**
Selenium library has a lot of Keywords we already support.
This should be a checklist which capabilities we can not replace, but should.

**Describe the solution you'd like**
The follow keywords of functionalities are not yet supported:

- [x] ! Alerts: Get Alert  as assertion, accept alert, wait for alert... #202 
- [x] ! Get Elements Size/Position #204 
- ! Upload and maybe Download a file 
  - [x] Upload #203 
  - [x] Download: #201
- [x] ! capture Element Screenshot Done in cce79beefe3762f63f75a87b3834dd33ce4a9664
- [x] ? get Source Done in ede2c0062a6be8cbbb7050938b800f3874a83f82
- [x] 🐭 Mouse (Up Down Move Click)
  - [ ] Move Mouse Over #218 
- [x] ? Get inner html
- [x] Keyword Events (in general, not related to element)
- [ ] Drag&Drop (playwright's mouse class might solve this) #205
- [ ] ? simulate Event
- [ ] ? Open Context Menu ???

That is basically it.
Elements with `!` are imho important 
`?` i have no idea if needed!

Not going to get implemented if there's no user needs that can't be solved with existing features
- [ ] ? Scroll Element Into View ( not sure if needed)
- [ ] ?Table Handling Keywords.? ( not sure if needed)
- [ ] ? submit form ?

**Comment by xylix** [comment]
´´´
Element Should Be Disabled
Element Should Be Enabled
Element Should Be Visible
Element Should Not Be Visible
Drag And Drop
Wait Until Location ...
Mouse Over
Mouse Out
Choose File
Handle Alert
Get Element Size
```
According to data from SL users these keywords have significant amounts of use and are not yet supported in robotframework-browser as of 4.8.2020

**Comment by xylix** [comment]
Element Should Be improvements and Mouse Over and Out are quite possible. 

Some questions:

Element.innerHTML should already work through `Get Attribute`. Is there a need to also be able to get whole page's innerHTML?

What exactly was meant by Keyword Events?

Could you or Niklas contribute some test templates where drag and drop is used?
