### ISSUE TITLE
MVP keywords

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#49]
Look at existing SeleniumLibrary keywords and figure out how to prioritize implementing them. Maybe create different tiers like "must have, nice to have, not a priority" or something like that.

Edit: added Tatu's list to this post for easier Kanban tracking
- [x] #50 Select from List keyword
- [x] Deselect from list (Might need to be programmed as custom JS)
- [ ] #54 Frame support. No idea how Playwright supports it, but it gets asked pretty often in SL side. Selecting frames and deselecting, no need to implement mistakes done in SL side tough. 
- [ ] #42 Support for opening multiple browsers/context/page
  - [ ] Try out solutions like `Switch Context` or using Open Browser to create new contexts - ask user input before committing to a technical solution
  - [ ] Switch Browser    alias_or_index
  - [ ] New Browser, New Context and New Page
- [x] Support for toggling check boxes and getting checkbox values. 
- [x] `Input Password` Same as input text but without any logging anywhere in any level.

Rene's Feature requests:
- [x]  ~~Type Text Fill Text~~ Instead added a parameter to `input text` to toggle typing / filling
- [x] ~~Press Key~~  added `Press Keys  selector *keys`
- [x] Wait until Element is     condition    selector     (condition could be clickable, unclickable, visible, invisible, enabled, disabled)

**Comment by aaltat** [comment]
- [ ] Select and deselect from list keywords.
- [ ] Support for toggling check boxes. 
- [ ] Frame support. No idea how Playwright supports it, but it gets asked pretty often in SL side. Selecting frames and deselecting, no need to implement mistakes done in SL side tough. 
- [ ] Support for opening multiple browsers/context/page
- [ ] `Input Password` Same as input text but without any logging anywhere in any level.

**Comment by xylix** [comment]
Work on list support started at https://github.com/MarketSquare/robotframework-browser/pull/50

**Comment by Snooz82** [comment]
I would say what is really missing at the moment is:
`Get Elements Attribute`
and 
`Get Text`

Assertions can be done with BuiltIn once you have the Text or the Attributes Content in a variable.

**Comment by Snooz82** [comment]
A list of Keyword i would like to see.

```
Open Browser   url=None   browser=chromium   alias=None   options=None
Close Browser
Go To      url
Get Url

Click Element    selector

Type Text    selector    text
Fill Text    selector     text

Get Text    selector
Get Attribute     selector

Press Key    selector    key
    
Switch Browser    alias_or_index

**Comment by xylix** [comment]
@Snooz82 There's now a `Press Keys` keyword and a `type: Boolean` parameter to `Input Text` to let users configure if they want to make input text type or fill the text. 

About `Press Keys`: I didn't really see a need to have a `Press Key` and a `Press Keys`, and it was quite easy to support the vararg version. Seleniumlibrary has also deprecated their `Press Key` in favor of a `Press Keys` KW. There's also a bit of upstream stuff to figure out with using `Shift + Key` as Press Keys parameter but otherwise it should be ready for use. Get Text and Get Attribute were also added this week, and some renamings were done.

When you can please give feedback if these keywords fill the needs you had for them. I updated the threads main post with your newer edited feature requests too.

**Comment by Snooz82** [comment]
* [x]  #50 Select from List keyword
* [x]  Deselect from list (Might need to be programmed as custom JS)
* [ ]  #54 Frame support. No idea how Playwright supports it, but it gets asked pretty often in SL side. Selecting frames and deselecting, no need to implement mistakes done in SL side tough.
* [ ]  #42 Support for opening multiple browsers/context/page
  
  * [ ]  Try out solutions like `Switch Context` or using Open Browser to create new contexts - ask user input before committing to a technical solution
  * [ ]  Switch Browser    alias_or_index
* [x]  Support for toggling check boxes and getting checkbox values.
* [x]  `Input Password` Same as input text but without any logging anywhere in any level.
* [x]   `Type Text`&  `Fill Text` ~Instead added a parameter to `input text` to toggle typing / filling~
* [x]  ~Press Key~  added `Press Keys  selector *keys`
* [x]  `Wait For Elements State`     condition    selector     (condition could be ~clickable~, ~unclickable~, visible, hidden, ~enabled~, ~disabled~, attached, detached)

**Comment by mkorpela** [comment]
`New Browser`, `New Context` and `New Page`

* Add new keywords To reflect Playwright browser/context/page levels
*  Create reasonable defaults. (This is problem with logging tough, which needs to be solved in some way)
* Browser/context level keywords only configure stuff in Playwright side.
*  | New Page | url | open the new Playwright page and navigates to the url
* `New Browser` does not create Playwright context or page
* `New Context` does not create Playwright page.

**Comment by xylix** [comment]
@mkorpela One way to log the "reasonable defaults" would be to log stuff like
``` Tried to GoTo without an open browser / context, implicitly opening a new context
New Browser
... logigng output
New Context
... logging output
``` 

So essentially we could just make all the "deeper level" keywords run the keywords to initialize the environment on the "above levels". Doing it by running keywords would also log everything. Altough it might also be confusing to the user, because then a test case like
``` Go To  index.html``` would actually run a bunch of keywords.

**Comment by mkorpela** [comment]
Good point :) Cascading behaviour should go only to level of New Page. Go To has valid cases to fail when window.close() is for example called by the tested / automated web page.

**Comment by xylix** [comment]
Closed in favour of #54 and #42
